ignore:
  - "*EnvironmentVariables*"
  - "**Exception*"
  - "**types/*"
  - "**/impl/thrift/*"
  - "**client/sqlexec/*"
  - "**Constants*"
  - "**/thrift/gen-java/org/apache/hive/service/rpc/thrift/*"
  - "**driver/DatabricksJdbcConstants*"
  - "**/client/impl/sdk/DatabricksMetadataSdkClient*" # TODO(PECO-1502): Remove once fixed