package com.databricks.jdbc.commons;

public enum MetricName {
  LIST_CATALOGS_METADATA,
  LIST_SCHEMAS_METADATA,
  LIST_TABLES_METADATA,
  LIST_COLUMNS_METADATA,
  LIST_TABLE_TYPES_METADATA,
  LIST_FUNCTIONS_METADATA,
  LIST_PRIMARY_KEYS_METADATA
}
