package com.databricks.jdbc.common;

public enum HTTPRequestType {
  UNKNOWN,
  THRIFT_OPEN_SESSION,
  THRIFT_CLOSE_SESSION,
  THRIFT_METADATA,
  THRIFT_CLOSE_OPERATION,
  THRIFT_CANCEL_OPERATION,
  THRIFT_EXECUTE_STATEMENT,
  THRIFT_FETCH_RESULTS,
  CLOUD_FETCH,
  VOLUME_LIST,
  VOLUME_SHOW_VOLUMES,
  VOLUME_GET,
  VOLUME_PUT,
  VOLUME_DELETE,
  AUTH,
  TELEMETRY_PUSH,
  OTHER
};
