package com.databricks.jdbc.common;

public enum HTTPRequestType {
  NOT_SET,
  THRIFT_OPEN_SESSION,
  THRIFT_CLOSE_SESSION,
  THRIFT_METADATA,
  THRIFT_CLOSE_OPERATION,
  THRIFT_CANCEL_OPERATION,
  THRIFT_EXECUTE_STATEMENT,
  THRIFT_FETCH_RESULTS,
  CLOUD_FETCH,
  UC_VOLUME_LIST,
  UC_VOLUME_SHOW_VOLUMES,
  UC_VOLUME_GET_TO,
  UC_VOLUME_PUT_INTO,
  UC_VOLUME_REMOVE,
  DBFS_VOLUME_EXECUTE_GET,
  DBFS_VOLUME_EXECUTE_PUT,
  DBFS_VOLUME_EXECUTE_DELETE,
  AUTH,
  TELEMETRY_PUSH,
  OTHER
};
