name: Weekly bug catcher

on:
  schedule:
    # Runs at 00:00 on every Monday
    - cron: '0 0 * * 1'

jobs:
  build-and-test:
    name: Build and Run Integration Tests
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    environment: azure-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Integration Tests
        run: mvn -B test -Dtest=*e2e/OAuthTests*
        env:
          DATABRICKS_HOST: ${{ secrets.JDBC_PAT_TEST_HOST_NAME }}
          DATABRICKS_HTTP_PATH: ${{ secrets.JDBC_PAT_TEST_HTTP_PATH }}
          DATABRICKS_USER: ${{ secrets.DATABRICKS_USER }}
          DATABRICKS_TOKEN: ${{ secrets.JDBC_PAT_TEST_TOKEN }}
          DATABRICKS_JDBC_M2M_CLIENT_ID: ${{ secrets.DATABRICKS_JDBC_M2M_CLIENT_ID }}
          DATABRICKS_JDBC_M2M_CLIENT_SECRET: ${{ secrets.DATABRICKS_JDBC_M2M_CLIENT_SECRET }}
          DATABRICKS_JDBC_M2M_HTTP_PATH: ${{ secrets.DATABRICKS_JDBC_M2M_HTTP_PATH }}
          DATABRICKS_JDBC_M2M_HOST: ${{ secrets.DATABRICKS_JDBC_M2M_HOST }}
          DATABRICKS_JDBC_SP_TOKEN_FED_HOST : ${{secrets.DATABRICKS_JDBC_SP_TOKEN_FED_HOST}}
          DATABRICKS_JDBC_SP_TOKEN_FED_HTTP_PATH : ${{secrets.DATABRICKS_JDBC_SP_TOKEN_FED_HTTP_PATH}}
          DATABRICKS_JDBC_SP_TOKEN_FED_CLIENT_ID : ${{secrets.DATABRICKS_JDBC_SP_TOKEN_FED_CLIENT_ID}}
          DATABRICKS_JDBC_SP_TOKEN_FED_CLIENT_SECRET : ${{secrets.DATABRICKS_JDBC_SP_TOKEN_FED_CLIENT_SECRET}}
          DATABRICKS_SP_TOKEN_FED_FEDERATION_ID : ${{secrets.DATABRICKS_SP_TOKEN_FED_FEDERATION_ID}}
          DATABRICKS_SP_TOKEN_FED_AZURE_TENANT_ID : ${{secrets.DATABRICKS_SP_TOKEN_FED_AZURE_TENANT_ID}}
