name: Weekly bug catcher

on:
  schedule:
    # Runs at 00:00 on every Monday
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Run Integration Tests
    runs-on: ubuntu-latest
    environment: azure-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up constants
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BENCHFOOD_HOST: ${{ secrets.DATABRICKS_BENCHFOOD_HOST }}
          DATABRICKS_BENCHMARKING_HOST: ${{ secrets.DATABRICKS_BENCHMARKING_HOST }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_BENCHFOOD_HTTP_PATH: ${{ secrets.DATABRICKS_BENCHFOOD_HTTP_PATH }}
          DATABRICKS_BENCHMARKING_HTTP_PATH: ${{ secrets.DATABRICKS_BENCHMARKING_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BENCHFOOD_TOKEN: ${{ secrets.DATABRICKS_BENCHFOOD_TOKEN }}
          DATABRICKS_BENCHMARKING_TOKEN: ${{ secrets.DATABRICKS_BENCHMARKING_TOKEN }}
          DATABRICKS_USER: ${{ secrets.DATABRICKS_USER }}
          DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
          DATABRICKS_SCHEMA: ${{ secrets.DATABRICKS_SCHEMA }}
          DATABRICKS_DOGFOOD_HOST: ${{ secrets.DATABRICKS_DOGFOOD_HOST }}
          DATABRICKS_DOGFOOD_TOKEN: ${{ secrets.DATABRICKS_DOGFOOD_TOKEN }}
          DATABRICKS_DOGFOOD_HTTP_PATH: ${{ secrets.DATABRICKS_DOGFOOD_HTTP_PATH }}
        run: |
          echo "DATABRICKS_HOST=${DATABRICKS_HOST}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHFOOD_HOST=${DATABRICKS_BENCHFOOD_HOST}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHMARKING_HOST=${DATABRICKS_BENCHMARKING_HOST}" >> $GITHUB_ENV
          echo "DATABRICKS_HTTP_PATH=${DATABRICKS_HTTP_PATH}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHFOOD_HTTP_PATH=${DATABRICKS_BENCHFOOD_HTTP_PATH}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHMARKING_HTTP_PATH=${DATABRICKS_BENCHMARKING_HTTP_PATH}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${DATABRICKS_TOKEN}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHFOOD_TOKEN=${DATABRICKS_BENCHFOOD_TOKEN}" >> $GITHUB_ENV
          echo "DATABRICKS_BENCHMARKING_TOKEN=${DATABRICKS_BENCHMARKING_TOKEN}" >> $GITHUB_ENV
          echo "DATABRICKS_USER=${DATABRICKS_USER}" >> $GITHUB_ENV
          echo "DATABRICKS_CATALOG=${DATABRICKS_CATALOG}" >> $GITHUB_ENV
          echo "DATABRICKS_SCHEMA=${DATABRICKS_SCHEMA}" >> $GITHUB_ENV
          echo "DATABRICKS_DOGFOOD_HOST=${DATABRICKS_DOGFOOD_HOST}" >> $GITHUB_ENV
          echo "DATABRICKS_DOGFOOD_TOKEN=${DATABRICKS_DOGFOOD_TOKEN}" >> $GITHUB_ENV
          echo "DATABRICKS_DOGFOOD_HTTP_PATH=${DATABRICKS_DOGFOOD_HTTP_PATH}" >> $GITHUB_ENV
          echo "DATABRICKS_JDBC_M2M_URL=${DATABRICKS_JDBC_M2M_URL}" >> $GITHUB_ENV
      - name: Run Integration Tests
        run: mvn -B test -Dtest=*e2e/*
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_BENCHFOOD_HOST: ${{ env.DATABRICKS_BENCHFOOD_HOST }}
          DATABRICKS_BENCHMARKING_HOST: ${{ env.DATABRICKS_BENCHMARKING_HOST }}
          DATABRICKS_HTTP_PATH: ${{ env.DATABRICKS_HTTP_PATH }}
          DATABRICKS_BENCHFOOD_HTTP_PATH: ${{ env.DATABRICKS_BENCHFOOD_HTTP_PATH }}
          DATABRICKS_BENCHMARKING_HTTP_PATH: ${{ env.DATABRICKS_BENCHMARKING_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
          DATABRICKS_BENCHFOOD_TOKEN: ${{ env.DATABRICKS_BENCHFOOD_TOKEN }}
          DATABRICKS_BENCHMARKING_TOKEN: ${{ env.DATABRICKS_BENCHMARKING_TOKEN }}
          DATABRICKS_USER: ${{ env.DATABRICKS_USER }}
          DATABRICKS_CATALOG: ${{ env.DATABRICKS_CATALOG }}
          DATABRICKS_SCHEMA: ${{ env.DATABRICKS_SCHEMA }}
          DATABRICKS_DOGFOOD_HOST: ${{ env.DATABRICKS_DOGFOOD_HOST }}
          DATABRICKS_DOGFOOD_TOKEN: ${{ env.DATABRICKS_DOGFOOD_TOKEN }}
          DATABRICKS_DOGFOOD_HTTP_PATH: ${{ env.DATABRICKS_DOGFOOD_HTTP_PATH }}
          DATABRICKS_JDBC_M2M_URL: ${{ env.DATABRICKS_JDBC_M2M_URL }}