name: Check for NEXT_CHANGELOG.md Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  check-next-changelog:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch list of changed files
        id: changed-files
        run: |
          files=$(git diff --name-only HEAD^ HEAD)
          echo "$files" > modified_files.txt

      - name: Fetch PR message
        id: pr-message
        run: |
          # Get PR number from GITHUB_REF
          PR_NUMBER=$(echo $GITHUB_REF | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/')
          
          # Use GitHub CLI to get PR body
          body=$(gh pr view $PR_NUMBER --json body -q '.body')
          echo "$body" > pr_message.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify NEXT_CHANGELOG.md was modified or PR message contains NO_CHANGELOG=true
        run: |
          modified_files=$(cat modified_files.txt)
          pr_message=$(cat pr_message.txt)

          echo "Changed files: $modified_files"

          if ! echo "$modified_files" | grep -q "NEXT_CHANGELOG.md"; then
            if echo "$pr_message" | grep -q "NO_CHANGELOG=true"; then
              echo "NO_CHANGELOG=true found in PR body."
              exit 0
            else
              echo "ERROR: NEXT_CHANGELOG.md not modified and NO_CHANGELOG=true not present."
              exit 1
            fi
          else
            echo "✅ NEXT_CHANGELOG.md was updated."
          fi

      - name: Comment on PR with instructions if needed
        if: failure()
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/')
          
          previous_comment_ids=$(gh api "repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
            --jq '.[] | select(.body | startswith("<!-- NEXT_CHANGELOG_INSTRUCTIONS -->")) | .id')

          if [ -z "$previous_comment_ids" ]; then
            gh pr comment $PR_NUMBER --body \
            "<!-- NEXT_CHANGELOG_INSTRUCTIONS -->
Please ensure that the \`NEXT_CHANGELOG.md\` file is updated with any relevant changes.  
If this is not necessary for your PR, include this in the PR body:

\`\`\`
NO_CHANGELOG=true
\`\`\`

and rerun the workflow."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete instructions comment on success
        if: success()
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/')
          
          previous_comment_ids=$(gh api "repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
            --jq '.[] | select(.body | startswith("<!-- NEXT_CHANGELOG_INSTRUCTIONS -->")) | .id')

          for comment_id in $previous_comment_ids; do
            gh api "repos/${{ github.repository }}/issues/comments/$comment_id" --method DELETE
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}