name: Check for NEXT_CHANGELOG.md Changes

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-next-changelog:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Checkout base branch (main)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Fetch list of changed files
        id: changed-files
        run: |
          files=$(git diff --name-only HEAD^ HEAD || git diff --name-only origin/main HEAD)
          echo "MODIFIED_FILES<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Verify NEXT_CHANGELOG.md was modified or PR message contains NO_CHANGELOG=true
        id: verify-changelog
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the latest PR data, including the body
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const PR_BODY = pullRequest.body || '';
            console.log('Latest PR body:', PR_BODY);
            
            // Check if NEXT_CHANGELOG.md is modified
            const modifiedFiles = process.env.MODIFIED_FILES || '';
            const changelogModified = modifiedFiles.includes('NEXT_CHANGELOG.md');
            
            if (!changelogModified) {
              if (PR_BODY.includes('NO_CHANGELOG=true')) {
                console.log("NO_CHANGELOG=true found in PR body.");
                core.exportVariable('CHANGELOG_NEEDED', 'false');
              } else {
                console.log("ERROR: NEXT_CHANGELOG.md not modified and NO_CHANGELOG=true not present.");
                core.exportVariable('CHANGELOG_NEEDED', 'true');
                core.setFailed("NEXT_CHANGELOG.md not modified and NO_CHANGELOG=true not present in PR body.");
              }
            } else {
              console.log("✅ NEXT_CHANGELOG.md was updated.");
              core.exportVariable('CHANGELOG_NEEDED', 'false');
            }

      - name: Comment on PR with instructions if needed
        if: failure() && env.CHANGELOG_NEEDED == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            // Check if we've already commented
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });
            
            const existingComment = comments.data.find(comment => 
              comment.body.includes('<!-- NEXT_CHANGELOG_INSTRUCTIONS -->')
            );
            
            if (!existingComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `<!-- NEXT_CHANGELOG_INSTRUCTIONS -->
                Please ensure that the \`NEXT_CHANGELOG.md\` file is updated with any relevant changes.  
                If this is not necessary for your PR, include this in the PR body:
                
                \`\`\`
                NO_CHANGELOG=true
                \`\`\`
                
                and rerun the workflow.`
              });
            }

      - name: Delete instructions comment on success
        if: success() && env.CHANGELOG_NEEDED == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });
            
            const existingComments = comments.data.filter(comment => 
              comment.body.includes('<!-- NEXT_CHANGELOG_INSTRUCTIONS -->')
            );
            
            for (const comment of existingComments) {
              await github.rest.issues.deleteComment({
                owner,
                repo,
                comment_id: comment.id
              });
            }