# This will run for all PRs
name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  formatting-check:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        java-version: [17, 20]  # 20 is the latest version as of 2023 and 17 is the latest LTS
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check formatting
        run: mvn --errors spotless:check

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        java-version: [17, 20]  # 20 is the latest version as of 2023 and 17 is the latest LTS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check Unit Tests
        run: mvn --errors test