name: Proxy Test with Dual Squid Proxies

on:
  workflow_dispatch:

jobs:
  proxy-test:
    runs-on: ubuntu-latest

    steps:
      ################################################################
      # 1) Check Out the Repo
      ################################################################
      - name: Checkout
        uses: actions/checkout@v4

      ################################################################
      # 2) Set Up Java
      ################################################################
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      ################################################################
      # 3) Install Squid Proxy
      ################################################################
      - name: Install Squid
        run: |
          sudo apt-get update
          sudo apt-get install -y squid

      ################################################################
      # 4) Configure the squid for SDK proxy (Port 3128)
      ################################################################
      - name: Configure Squid (Primary 3128)
        run: |
          echo "
          http_port 3128
          # Restrict to localhost for security
          acl localnet src 127.0.0.1/32
          http_access allow localnet
          http_access deny all
          " | sudo tee /etc/squid/squid.conf

      ################################################################
      # 5) Start the squid for SDK proxy
      ################################################################
      - name: Start the squid for SDK proxy
        run: |
          sudo systemctl restart squid
          sudo systemctl enable squid

      ################################################################
      # 6) Wait for the squid for SDK proxy to be Ready
      ################################################################
      - name: Wait for Squid (3128)
        run: |
          for i in {1..5}; do
            echo "Checking if Squid on 3128 is up (attempt $i)..."
            if curl -x http://localhost:3128 http://example.com -sSf -o /dev/null; then
              echo "Squid on 3128 is up."
              break
            fi
            if [ $i -eq 5 ]; then
              echo "Squid on 3128 did not respond after 5 attempts. Failing..."
              exit 1
            fi
            sleep 5
          done

      ################################################################
      # 7) Configure a squid for cloudfetch proxy (Port 8889) with Unique PID and Cache
      ################################################################
      - name: Configure squid for cloudfetch proxy (Cloud Fetch 8889)
        run: |
          sudo cp /etc/squid/squid.conf /etc/squid/squid2.conf
          # Update the port to 8889 in the new config
          sudo sed -i 's/http_port 3128/http_port 8889/' /etc/squid/squid2.conf
          # Set unique PID file and cache directory for the second instance
          echo "pid_filename /var/run/squid2.pid" | sudo tee -a /etc/squid/squid2.conf
          echo "cache_dir ufs /var/spool/squid2 100 16 256" | sudo tee -a /etc/squid/squid2.conf
          sudo sed -i 's/\/var\/log\/squid/\/var\/log\/squid2/g' /etc/squid/squid2.conf
          sudo mkdir -p /var/log/squid2
          sudo chown proxy:proxy /var/log/squid2

      ################################################################
      # 8) Initialize Cache Directory for squid for cloudfetch proxy
      ################################################################
      - name: Initialize Cache for squid for cloudfetch proxy
        run: |
          # Create the cache directory if it doesn't exist
          sudo mkdir -p /var/spool/squid2
          sudo chown proxy:proxy /var/spool/squid2
          # Initialize the cache directories as per the second config
          sudo squid -f /etc/squid/squid2.conf -z

      ################################################################
      # 9) Start the squid for cloudfetch proxy
      ################################################################
      - name: Start the squid for cloudfetch proxy
        run: |
          # Run the squid for cloudfetch proxy instance with its own config
          sudo squid -f /etc/squid/squid2.conf -N &> /tmp/squid2.log &
          # Wait a bit to let it start
          sleep 3

      ################################################################
      # 10) Wait for the squid for cloudfetch proxy (8889)
      ################################################################
      - name: Verify Squid (8889)
        run: |
          for i in {1..5}; do
            echo "Checking if Squid on 8889 is up (attempt $i)..."
            if curl -x http://localhost:8889 http://example.com -sSf -o /dev/null; then
              echo "squid for cloudfetch proxy on 8889 is up."
              break
            fi
            if [ $i -eq 5 ]; then
              echo "Squid on 8889 did not respond after 5 attempts. Failing..."
              cat /tmp/squid2.log
              exit 1
            fi
            sleep 5
          done

      ################################################################
      # 11) Maven Build
      ################################################################
      - name: Maven Build
        run: mvn clean package

      ################################################################
      # 12) Set Environment Variables for Tests
      ################################################################
      - name: Set Environment Variables
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          PROXY_URL: "http://localhost:3128"
          CF_PROXY_URL: "http://localhost:8889"

        run: echo "Environment variables set. Tokens/hosts ready."

      ################################################################
      # 13) Run Proxy Tests
      ################################################################
      - name: Run ProxyTest
        run: |
          mvn test -Dtest=**/ProxyTest.java 

      ################################################################
      # 14) Upload Logs
      ################################################################
      - name: Upload Proxy Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: proxy-test-logs
          path: |
            test-results/
            /var/log/squid/access.log
            /var/log/squid/cache.log
            /var/log/squid2/
            /tmp/squid2.log

      ################################################################
      # 15) Cleanup
      ################################################################
      - name: Cleanup Squid
        if: always()
        run: |
          echo "Stopping and disabling primary Squid..."
          sudo systemctl stop squid
          sudo systemctl disable squid
          echo "Killing squid for cloudfetch proxy if still running..."
          sudo pkill squid
