name: Integration Tests Workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Run Integration Tests
    runs-on: ubuntu-latest
    environment: azure-prod
    strategy:
      matrix:
        include:
          - test-command: mvn -B clean compile test -Dtest=*IntegrationTests
            token-secret: DATABRICKS_TOKEN
            use-thrift-client: 'false'
          - test-command: mvn -B clean compile test -Dtest=**/fakeservice/tests/*.java,!**/fakeservice/tests/ConcurrencyIntegrationTests.java,!**/fakeservice/tests/PreparedStatementIntegrationTests.java,!**/fakeservice/tests/UCVolumeIntegrationTests.java
            token-secret: THRIFT_DATABRICKS_TOKEN
            use-thrift-client: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Run Integration Tests
        run: ${{ matrix.test-command }}
        env:
          DATABRICKS_TOKEN: ${{ secrets[matrix.token-secret] }}
          DATABRICKS_USER: ${{ secrets.DATABRICKS_USER }}
          USE_THRIFT_CLIENT: ${{ matrix.use-thrift-client }}
