name: Update Version and Create PR

on:
  workflow_dispatch:
    inputs:
      old_version:
        description: 'Old version to replace'
        required: true
      new_version:
        description: 'New version to update to'
        required: true
  pull_request:

jobs:
  update-version:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW }}
          persist-credentials: true

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch for version update
        id: create_branch
        run: |
          BRANCH_NAME="version-update-${{ github.event.inputs.new_version }}"
          git checkout -b "$BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Replace old version with new version in repository
        run: |
#          OLD_VERSION="${{ github.event.inputs.old_version }}"
#          NEW_VERSION="${{ github.event.inputs.new_version }}"
          OLD_VERSION="0.9.9"
          NEW_VERSION="1.0.0"
          grep -rl "$OLD_VERSION" . | xargs sed -i "s/$OLD_VERSION/$NEW_VERSION/g" || echo "No occurrences found."

      - name: Commit changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update version from ${{ github.event.inputs.old_version }} to ${{ github.event.inputs.new_version }}"
          else
            echo "No changes to commit."
          fi

      - name: Push branch
        run: |
          BRANCH_NAME=${{ steps.create_branch.outputs.branch }}
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW }}
          branch: ${{ steps.create_branch.outputs.branch }}
          title: "Update version from ${{ github.event.inputs.old_version }} to ${{ github.event.inputs.new_version }}"
          body: |
            This PR updates all references from version `${{ github.event.inputs.old_version }}` to `${{ github.event.inputs.new_version }}`.
          labels: version-update
